Repository mocacong/Mocacong-Backend, pull requests merged in 2023-07, with the labels that each got.

#115 feat: 내가 리뷰를 작성한 카페 조회 시 작성한 리뷰의 studyType이 반환되게끔 기능 수정
  src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경, 리팩터링

#118 feat: 공백 값에 대한 토큰 공백 커스텀 예외 처리 추가
  src/main/java/mocacong/server/exception/badrequest/BlankTokenException.java
  src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
  src/test/java/mocacong/server/security/auth/AuthorizationExtractorTest.java
Labels: 사소한 버그

#117 feat : 한 사용자가 총 3개 보다 많은 이미지를 등록할 수 없도록 기능 구현
  .gitignore
  src/main/java/mocacong/server/exception/badrequest/ExceedCafeImagesCountsException.java
  src/main/java/mocacong/server/exception/badrequest/ExceedCageImagesTotalCountsException.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#119 feat: 로그 마스킹 처리에 이메일 제외
  src/main/resources/logback-spring.xml
Labels: 기능 구현, 인프라

#120 feat: cafeImage 즉시로딩에서 지연로딩으로 변경
  src/main/java/mocacong/server/domain/Cafe.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 리팩터링

#121 feat: 코멘트 첫페이지 조회 시 전체 코멘트 개수 반환 기능 구현
  src/main/java/mocacong/server/dto/response/CommentsResponse.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: api 변경

#122 feat: 댓글 좋아요 등록 기능 구현
  src/main/java/mocacong/server/controller/CommentLikeController.java
  src/main/java/mocacong/server/domain/CommentLike.java
  src/main/java/mocacong/server/dto/response/CommentLikeSaveResponse.java
  src/main/java/mocacong/server/exception/badrequest/AlreadyExistsCommentLike.java
  src/main/java/mocacong/server/exception/badrequest/InvalidCommentLikeException.java
  src/main/java/mocacong/server/exception/notfound/NotFoundCommentLikeException.java
  src/main/java/mocacong/server/repository/CommentLikeRepository.java
  src/main/java/mocacong/server/service/CommentLikeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/main/java/mocacong/server/service/event/DeleteCommentEvent.java
  src/test/java/mocacong/server/acceptance/CommentLikeAcceptanceTest.java
  src/test/java/mocacong/server/repository/CommentLikeRepositoryTest.java
  src/test/java/mocacong/server/repository/CommentRepositoryTest.java
  src/test/java/mocacong/server/service/CommentLikeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CommentLikeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: 기능 구현

#124 feat: CafeImage 등록시 등록된 id 함께 반환 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
  src/main/java/mocacong/server/dto/response/CafeImagesSaveResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#125 fix: 카페 세부정보 콘센트, 책상 필드 @NotNull 추가
  src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
  src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
Labels: api 변경

#123 feat: 코멘트 신고 기능 POST API 구현
  src/main/java/mocacong/server/config/BatchConfig.java
  src/main/java/mocacong/server/controller/ReportController.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/domain/Report.java
  src/main/java/mocacong/server/domain/ReportReason.java
  src/main/java/mocacong/server/domain/Status.java
  src/main/java/mocacong/server/dto/request/CommentReportRequest.java
  src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
  src/main/java/mocacong/server/dto/response/CafeReviewResponse.java
  src/main/java/mocacong/server/dto/response/CommentReportResponse.java
  src/main/java/mocacong/server/dto/response/CommentSaveResponse.java
  src/main/java/mocacong/server/dto/response/FavoriteSaveResponse.java
  src/main/java/mocacong/server/dto/response/OAuthTokenResponse.java
  src/main/java/mocacong/server/dto/response/TokenResponse.java
  src/main/java/mocacong/server/exception/badrequest/DuplicateReportCommentException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidCommentReportException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidReportReasonException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidStatusException.java
  src/main/java/mocacong/server/exception/unauthorized/InactiveMemberException.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/repository/ReportRepository.java
  src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/service/ReportService.java
  src/main/java/mocacong/server/service/event/DeleteCommentEvent.java
  src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/ReportAcceptanceTest.java
  src/test/java/mocacong/server/repository/MemberRepositoryTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
  src/test/java/mocacong/server/service/ReportConcurrentServiceTest.java
  src/test/java/mocacong/server/service/ReportServiceTest.java
Labels: api 변경, 기능 구현

#129 fix: 카페 이미지 등록 response에서 userReportCount 제거
  src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
  src/main/java/mocacong/server/service/CafeService.java
Labels: api 변경

#128 feat: 카페 이미지 신고 기능 POST API 구현
  src/main/java/mocacong/server/controller/ReportController.java
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Report.java
  src/main/java/mocacong/server/dto/request/CafeImageReportRequest.java
  src/main/java/mocacong/server/dto/response/CafeImageReportResponse.java
  src/main/java/mocacong/server/exception/badrequest/DuplicateReportCafeImageException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidCafeImageReportException.java
  src/main/java/mocacong/server/repository/CafeImageRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/ReportService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/ReportConcurrentServiceTest.java
  src/test/java/mocacong/server/service/ReportServiceTest.java
Labels: 기능 구현

#130 fix: 회원 경고 추가 기준 수정
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/service/ReportService.java
  src/test/java/mocacong/server/service/ReportServiceTest.java
Labels: api 변경
