Repository mocacong/Mocacong-Backend, pull requests merged in 2023-04, with the labels that each got.

#25 feat: 카페 목록 필터링 조회 get api 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/request/CafeFilterRequest.java
  src/main/java/mocacong/server/dto/response/CafeFilterResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#26 feat: 카페 즐겨찾기 등록 api 구현
  src/main/java/mocacong/server/controller/FavoriteController.java
  src/main/java/mocacong/server/domain/Favorite.java
  src/main/java/mocacong/server/dto/response/FavoriteSaveResponse.java
  src/main/java/mocacong/server/dto/response/FindCafeResponse.java
  src/main/java/mocacong/server/exception/badrequest/AlreadyExistsFavorite.java
  src/main/java/mocacong/server/repository/FavoriteRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
  src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
Labels: api 변경, 기능 구현

#27 feat: 초성, 중성, 종성 분리 닉네임 검증 허용
  src/main/java/mocacong/server/domain/Member.java
  src/test/java/mocacong/server/domain/MemberTest.java
Labels: api 변경

#29 fix: 특정 카페 조회 api response 변경
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeDetail.java
  src/main/java/mocacong/server/dto/response/FindCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/domain/CafeDetailTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/resources/application.yml
Labels: api 변경

#31 feat: 마이페이지 조회 api 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/MyPageResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#30 feat: 생성 및 수정 시각 저장 엔티티 구현
  src/main/java/mocacong/server/config/BaseTimeConfig.java
  src/main/java/mocacong/server/domain/BaseTime.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Favorite.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/Score.java
  src/main/java/mocacong/server/domain/StudyType.java
  src/test/java/mocacong/server/domain/BaseTimeTest.java
  src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
  src/test/java/mocacong/server/repository/RepositoryTest.java
  src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
  src/test/java/mocacong/server/repository/StudyTypeRepositoryTest.java
Labels: 기능 구현

#32 feat: 스프링 애플리케이션 time zone 설정
  src/main/java/mocacong/server/config/BaseTimeConfig.java
  src/test/java/mocacong/server/domain/BaseTimeTest.java
Labels: 기능 구현, 사소한 버그

#33 feat: 카페 즐겨찾기 해제 delete api 구현
  src/main/java/mocacong/server/controller/FavoriteController.java
  src/main/java/mocacong/server/exception/notfound/NotFoundFavoriteException.java
  src/main/java/mocacong/server/repository/FavoriteRepository.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
Labels: 기능 구현

#35 feat: 서버 에러 발생 시 슬랙 알림 기능 구현
  build.gradle
  src/main/java/mocacong/server/controller/ControllerAdvice.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 기능 구현, 인프라

#34 feat: OAuth Apple 로그인 api 구현
  build.gradle
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/config/FeignClientConfig.java
  src/main/java/mocacong/server/controller/AuthController.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/domain/Platform.java
  src/main/java/mocacong/server/dto/request/AppleLoginRequest.java
  src/main/java/mocacong/server/dto/request/OAuthMemberSignUpRequest.java
  src/main/java/mocacong/server/dto/response/AppleTokenResponse.java
  src/main/java/mocacong/server/dto/response/OAuthMemberSignUpResponse.java
  src/main/java/mocacong/server/exception/badrequest/InvalidPlatformException.java
  src/main/java/mocacong/server/exception/unauthorized/InvalidTokenException.java
  src/main/java/mocacong/server/exception/unauthorized/TokenExpiredException.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/security/EncryptUtils.java
  src/main/java/mocacong/server/security/auth/apple/AppleClaimsValidator.java
  src/main/java/mocacong/server/security/auth/apple/AppleClient.java
  src/main/java/mocacong/server/security/auth/apple/AppleJwtParser.java
  src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
  src/main/java/mocacong/server/security/auth/apple/ApplePlatformMemberResponse.java
  src/main/java/mocacong/server/security/auth/apple/ApplePublicKey.java
  src/main/java/mocacong/server/security/auth/apple/ApplePublicKeys.java
  src/main/java/mocacong/server/security/auth/apple/PublicKeyGenerator.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/support/AwsS3Uploader.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/domain/MemberTest.java
  src/test/java/mocacong/server/domain/PlatformTest.java
  src/test/java/mocacong/server/repository/MemberRepositoryTest.java
  src/test/java/mocacong/server/security/EncryptUtilsTest.java
  src/test/java/mocacong/server/security/auth/apple/AppleClaimsValidatorTest.java
  src/test/java/mocacong/server/security/auth/apple/AppleClientTest.java
  src/test/java/mocacong/server/security/auth/apple/AppleJwtParserTest.java
  src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
  src/test/java/mocacong/server/security/auth/apple/ApplePublicKeysTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: api 변경, 기능 구현

#36 feat: JSON 파싱 예외 핸들러 구현
  src/main/java/mocacong/server/controller/ControllerAdvice.java
Labels: 기능 구현, 사소한 버그

#37 feat: ContentType 관련 예외 핸들링 구현
  src/main/java/mocacong/server/controller/ControllerAdvice.java
Labels: 기능 구현, 사소한 버그

#41 fix: Apple OAuth 최종 회원가입 로직 수정
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/service/AuthService.java
  src/test/java/mocacong/server/domain/MemberTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
Labels: 사소한 버그, ❗️긴급 구현❗️

#40 feat: CORS 이슈 해결 적용
  src/main/java/mocacong/server/config/SecurityConfig.java
  src/main/java/mocacong/server/config/WebConfig.java
Labels: 인프라

#39 feat: 이메일 인증 코드 전송 api 구현
  build.gradle
  src/main/java/mocacong/server/config/AsyncConfig.java
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/request/EmailVerifyCodeRequest.java
  src/main/java/mocacong/server/dto/response/EmailVerifyCodeResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/support/AwsSESSender.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/verify-email.html
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: 기능 구현, 인프라

#42 feat: 카페 코멘트 수정 put api 구현
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/dto/request/CommentUpdateRequest.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: 기능 구현

#43 feat: HttpRequestMethodNotSupportedException 예외 핸들링 구현
  src/main/java/mocacong/server/controller/ControllerAdvice.java
Labels: 사소한 버그

#44 fix: 리뷰나 댓글 작성한 회원탈퇴가 불가능한 버그 수정
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/Score.java
  src/main/java/mocacong/server/exception/badrequest/InvalidCommentUpdateException.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/repository/ReviewRepository.java
  src/main/java/mocacong/server/repository/ScoreRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/service/event/MemberEvent.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: 🚨심각한 버그🚨, 리팩터링

#48 feat: 카페 코멘트 목록 조회 api 구현
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/dto/response/CommentsResponse.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: api 변경, 기능 구현

#47 feat: 마이페이지에서 즐겨찾기한 카페 목록 조회 api 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafesResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#50 fix: BaseTime 컬럼 타입 TimeStamp로 변경
  src/main/java/mocacong/server/domain/BaseTime.java
  src/test/java/mocacong/server/domain/BaseTimeTest.java
Labels: 사소한 버그

#49 feat: 카페 이미지 등록 POST api 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#52 feat: 회원 전체삭제 관련 로직 및 api 삭제
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: api 변경

#53 feat: 특정 카페 코멘트 중 나의 코멘트만 조회하는 api 구현
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: 기능 구현
