Repository mocacong/Mocacong-Backend, pull requests merged in 2023-05, with the labels that each got.

#54 fix: 이메일 뿐 아니라 닉네임이 중복되면 가입하지 못하도록 변경
  src/main/java/mocacong/server/exception/badrequest/DuplicateNicknameException.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 사소한 버그

#51 feat: kakao OAuth 로그인 api 구현
  src/main/java/mocacong/server/controller/AuthController.java
  src/main/java/mocacong/server/dto/request/KakaoLoginRequest.java
  src/main/java/mocacong/server/dto/response/OAuthTokenResponse.java
  src/main/java/mocacong/server/security/auth/OAuthPlatformMemberResponse.java
  src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoAccessToken.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoAccessTokenClient.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoAccessTokenRequest.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoUser.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoUserClient.java
  src/main/java/mocacong/server/security/auth/kakao/KakaoUserRequest.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
  src/test/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProviderTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
  src/test/resources/application.yml
Labels: 기능 구현

#56 feat: 도커 이미지 기반 github action 배포 자동화 구현
  .github/workflows/cd-backend.yml
  docker-compose.yml
  dockerfile
  src/main/resources/application-prod.yml
Labels: 인프라

#57 feat: 내가 작성한 특정 카페 리뷰 조회 api 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/response/CafeMyReviewResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#59 fix: 카페 리뷰 작성 시 스터디타입에 `both` 선택이 가능하도록 로직 수정
  src/main/java/mocacong/server/domain/Cafe.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#60 feat: 프로필 회원정보 수정 PUT api 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/dto/request/MemberProfileUpdateRequest.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#55 feat: 카페 이미지 조회 GET API 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/dto/response/CafeImageResponse.java
  src/main/java/mocacong/server/dto/response/CafeImagesResponse.java
  src/main/java/mocacong/server/dto/response/FindCafeResponse.java
  src/main/java/mocacong/server/repository/CafeImageRepository.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
  src/test/java/mocacong/server/repository/MemberRepositoryTest.java
  src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/support/DatabaseCleaner.java
Labels: 기능 구현

#61 feat: 카페 코멘트 조회 시 코멘트 id 또한 조회하도록 로직 수정
  src/main/java/mocacong/server/dto/response/CommentResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
Labels: api 변경

#46 fix: SpringSecurity 인증 더블 체크 버그 수정
  build.gradle
  src/main/java/mocacong/server/config/SecurityConfig.java
Labels: 사소한 버그, 리팩터링

#63 fix: KAKAO OAuth 플랫폼이 잘못 저장되는 버그 및 인가코드 예외 핸들링 구현
  src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
  src/main/java/mocacong/server/service/AuthService.java
  src/test/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProviderTest.java
Labels: 🚨심각한 버그🚨, 기능 구현, ❗️긴급 구현❗️

#64 fix: 카페 세부정보 계산 로직 최대값에서 평균점수로 변경
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/cafedetail/Desk.java
  src/main/java/mocacong/server/domain/cafedetail/Parking.java
  src/main/java/mocacong/server/domain/cafedetail/Power.java
  src/main/java/mocacong/server/domain/cafedetail/Sound.java
  src/main/java/mocacong/server/domain/cafedetail/Toilet.java
  src/main/java/mocacong/server/domain/cafedetail/Wifi.java
  src/test/java/mocacong/server/domain/CafeTest.java
Labels: api 변경

#68 feat: 카페 코멘트 삭제 DELETE API 구현
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/exception/badrequest/InvalidCommentDeleteException.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: 기능 구현

#67 feat: 작성 코멘트 목록 조회 GET API 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyCommentCafesResponse.java
  src/main/java/mocacong/server/repository/CommentRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#65 feat: 리뷰 남긴 카페 목록 조회 GET API 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyReviewCafesResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/repository/ScoreRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/repository/ScoreRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#69 feat: 에러 발생 시 슬랙 알람을 비동기로 보내도록 구현
  src/main/java/mocacong/server/controller/ControllerAdvice.java
  src/main/java/mocacong/server/support/SlackAlarmGenerator.java
Labels: 리팩터링

#71 feat: 개발 서버와 운영 서버 분리
  src/main/resources/application-dev.yml
  src/main/resources/logback-spring.xml
Labels: 인프라

#72 feat: 비밀번호 확인 인증 POST API 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/request/PasswordVerifyRequest.java
  src/main/java/mocacong/server/dto/response/PasswordVerifyResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#73 feat: LoginInterceptor 적용 경로 변경
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/security/auth/LoginInterceptor.java
Labels: 인프라, 리팩터링

#74 feat: 이메일 인증 api 내 검증 로직 추가 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/request/EmailVerifyCodeRequest.java
  src/main/java/mocacong/server/dto/response/EmailVerifyCodeResponse.java
  src/main/java/mocacong/server/exception/badrequest/InvalidNonceException.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: api 변경

#77 fix: 마이페이지 참여 카페 반환 시 `mapId` 필드 추가하도록 수정
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
Labels: api 변경

#75 fix: 페이지네이션 API 응답 필드 `currentPage` -> `isEnd`로 변경
  src/main/java/mocacong/server/dto/response/CafeImagesResponse.java
  src/main/java/mocacong/server/dto/response/CommentsResponse.java
  src/main/java/mocacong/server/dto/response/MyCommentCafesResponse.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafesResponse.java
  src/main/java/mocacong/server/dto/response/MyReviewCafesResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
Labels: api 변경

#78 feat: MaxUploadSizeExceededException 예외 처리 추가
  src/main/java/mocacong/server/controller/ControllerAdvice.java
  src/main/java/mocacong/server/support/AwsS3Uploader.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/resources/application.yml
Labels: 사소한 버그

#79 feat: 카페 정보 미리보기 조회 GET API 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/response/PreviewCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#82 feat: 프로필 수정 페이지 조회 GET API 구현
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/GetUpdateProfileInfoResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#81 fix: 이메일 인증 및 비밀번호 변경 API 에서 token 필요하도록 변경
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/request/ResetPasswordRequest.java
  src/main/java/mocacong/server/dto/response/EmailVerifyCodeResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: api 변경

#84 fix: 우분투 서버에서 메일 경로 인식 못하는 버그 수정
  build.gradle
  src/main/java/mocacong/server/exception/badrequest/InvalidNonceException.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/support/AwsSESSender.java
  src/main/java/mocacong/server/support/EmailHtmlContent.java
  src/main/resources/logback-spring.xml
Labels: 사소한 버그

#85 fix: studyType별로 카페 필터링 조회 API - POST API로 수정
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/request/CafeFilterStudyTypeRequest.java
  src/main/java/mocacong/server/dto/response/CafeFilterStudyTypeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#87 feat: 즐겨찾기한 카페 필터링 조회 POST API 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/dto/request/CafeFilterFavoritesRequest.java
  src/main/java/mocacong/server/dto/response/CafeFilterFavoritesResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#86 feat: Elasticache for Redis를 도입하여 캐싱 적용
  build.gradle
  src/main/java/mocacong/server/config/RedisCacheConfig.java
  src/main/java/mocacong/server/config/RedisConfig.java
  src/main/java/mocacong/server/security/auth/apple/AppleClient.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/mocacong/server/acceptance/AcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/ServiceTest.java
  src/test/java/mocacong/server/support/DatabaseCleaner.java
  src/test/java/mocacong/server/support/TestRedisConfig.java
  src/test/resources/application.yml
Labels: 기능 구현, 인프라, 리팩터링

#89 fix: 내가 작성한 특정 카페 리뷰 조회 GET API 수정
  src/main/java/mocacong/server/dto/response/CafeMyReviewResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
Labels: api 변경

#90 feat: 카페 이미지를 요청 당 3개까지 올릴 수 있도록 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/exception/badrequest/ExceedCafeImagesCountsException.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경, 기능 구현
