Repository mocacong/Mocacong-Backend, pull requests merged in 2023-03, with the labels that each got.

#2 docs: Git 풀 리퀘스트 템플릿 문서 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서화

#3 feat: github actions CI 스크립트 작성
  .github/workflows/ci-backend.yml
Labels: 인프라

#4 feat: 비밀번호 암호화 로직 구현
  build.gradle
  src/main/java/mocacong/server/ServerApplication.java
  src/main/java/mocacong/server/config/SecurityConfig.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/dto/request/MemberSignUpRequest.java
  src/main/java/mocacong/server/exception/badrequest/BadRequestException.java
  src/main/java/mocacong/server/exception/badrequest/DuplicateMemberException.java
  src/main/java/mocacong/server/exception/notfound/NotFoundException.java
  src/main/java/mocacong/server/exception/notfound/NotFoundMemberException.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/mocacong/server/ServerApplicationTests.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#7 feat: swagger 환경설정 및 api 적용
  build.gradle
  src/main/java/mocacong/server/config/SwaggerConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/resources/application.yml
Labels: 문서화, 기능 구현

#6 feat: 카페 관련 엔티티 작성
  src/main/java/mocacong/server/config/SecurityConfig.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeDetail.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/domain/Coordinate.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/Score.java
  src/main/java/mocacong/server/domain/cafedetail/Desk.java
  src/main/java/mocacong/server/domain/cafedetail/Parking.java
  src/main/java/mocacong/server/domain/cafedetail/Power.java
  src/main/java/mocacong/server/domain/cafedetail/Sound.java
  src/main/java/mocacong/server/domain/cafedetail/StudyType.java
  src/main/java/mocacong/server/domain/cafedetail/Toilet.java
  src/main/java/mocacong/server/domain/cafedetail/Tumbler.java
  src/main/java/mocacong/server/domain/cafedetail/Wifi.java
  src/main/java/mocacong/server/exception/badrequest/BadRequestException.java
  src/main/java/mocacong/server/exception/badrequest/DuplicateMemberException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidDeskException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidParkingException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidPowerException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidScoreException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidSoundException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidStudyTypeException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidToiletException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidTumblerException.java
  src/main/java/mocacong/server/exception/badrequest/InvalidWifiException.java
  src/main/java/mocacong/server/exception/notfound/NotFoundException.java
  src/main/java/mocacong/server/exception/notfound/NotFoundMemberException.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/domain/CoordinateTest.java
  src/test/java/mocacong/server/domain/ScoreTest.java
Labels: 기능 구현

#8 feat: 로그인 및 토큰 발급 POST api 구현
  build.gradle
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/config/SecurityConfig.java
  src/main/java/mocacong/server/controller/AuthController.java
  src/main/java/mocacong/server/dto/LoginUserEmail.java
  src/main/java/mocacong/server/dto/request/AuthLoginRequest.java
  src/main/java/mocacong/server/dto/response/TokenResponse.java
  src/main/java/mocacong/server/exception/InputFieldException.java
  src/main/java/mocacong/server/exception/MocacongException.java
  src/main/java/mocacong/server/exception/badrequest/PasswordMismatchException.java
  src/main/java/mocacong/server/exception/notfound/NoSuchMemberException.java
  src/main/java/mocacong/server/exception/unauthorized/InvalidBearerException.java
  src/main/java/mocacong/server/exception/unauthorized/InvalidTokenException.java
  src/main/java/mocacong/server/exception/unauthorized/TokenExpiredException.java
  src/main/java/mocacong/server/security/auth/AuthenticationPrincipalArgumentResolver.java
  src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
  src/main/java/mocacong/server/security/auth/JwtTokenProvider.java
  src/main/java/mocacong/server/security/auth/LoginInterceptor.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/resources/application.yml
  src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
  src/test/java/mocacong/server/security/auth/JwtTokenProviderTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
Labels: 기능 구현

#9 feat: 통합 및 인수테스트 격리 틀 세팅 구현
  src/main/java/mocacong/server/domain/Score.java
  src/test/java/mocacong/server/acceptance/AcceptanceTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
  src/test/java/mocacong/server/service/ServiceTest.java
  src/test/java/mocacong/server/support/DatabaseCleaner.java
  src/test/java/mocacong/server/support/DatabaseCleanerCallback.java
Labels: 테스트

#10 feat: 회원탈퇴 DELETE api 구현
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/security/auth/AuthenticationPrincipalArgumentResolver.java
  src/main/java/mocacong/server/security/auth/LoginUserEmail.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#12 feat: 회원가입 시 중복체크 api 구현
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/IsDuplicateEmailResponse.java
  src/main/java/mocacong/server/dto/response/IsDuplicateNicknameResponse.java
  src/main/java/mocacong/server/exception/badrequest/InvalidEmailException.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#13 feat: 회원 전체조회 api 구현
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/dto/response/MemberGetAllResponse.java
  src/main/java/mocacong/server/dto/response/MemberGetResponse.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#15 fix: 중복체크 api의 잘못된 response spec을 `api docs`와 통일
  src/main/java/mocacong/server/dto/response/IsDuplicateEmailResponse.java
  src/main/java/mocacong/server/dto/response/IsDuplicateNicknameResponse.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 사소한 버그

#14 feat: 회원 전체삭제 delete api 구현
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 기능 구현

#16 feat: 텀블러 할인 정보 제거
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeDetail.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/cafedetail/Tumbler.java
  src/main/java/mocacong/server/exception/badrequest/InvalidTumblerException.java
  src/test/java/mocacong/server/domain/CafeTest.java
Labels: api 변경

#17 feat: 카페 등록 post api 구현
  src/main/java/mocacong/server/config/AuthConfig.java
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/Coordinate.java
  src/main/java/mocacong/server/dto/request/CafeRegisterRequest.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/security/auth/LoginInterceptor.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/domain/CoordinateTest.java
  src/test/java/mocacong/server/domain/ScoreTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#18 fix: 브랜치 병합으로 인한 Cafe 테스트 깨지는 현상 수정
  src/test/java/mocacong/server/domain/CafeTest.java
Labels: 사소한 버그

#19 feat: 카페 정보 조회 api 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/CafeDetail.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/StudyType.java
  src/main/java/mocacong/server/domain/cafedetail/StudyType.java
  src/main/java/mocacong/server/dto/response/CommentResponse.java
  src/main/java/mocacong/server/dto/response/FindCafeResponse.java
  src/main/java/mocacong/server/dto/response/ReviewResponse.java
  src/main/java/mocacong/server/exception/notfound/NotFoundCafeException.java
  src/main/java/mocacong/server/repository/ScoreRepository.java
  src/main/java/mocacong/server/repository/StudyTypeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/resources/application-prod.yml
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/domain/StudyTypeTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#20 feat: 카페에 대한 리뷰 작성 api 구현
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/domain/StudyType.java
  src/main/java/mocacong/server/domain/cafedetail/Desk.java
  src/main/java/mocacong/server/domain/cafedetail/Parking.java
  src/main/java/mocacong/server/domain/cafedetail/Power.java
  src/main/java/mocacong/server/domain/cafedetail/Sound.java
  src/main/java/mocacong/server/domain/cafedetail/Toilet.java
  src/main/java/mocacong/server/domain/cafedetail/Wifi.java
  src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
  src/main/java/mocacong/server/dto/response/CafeReviewResponse.java
  src/main/java/mocacong/server/exception/badrequest/AlreadyExistsCafeReview.java
  src/main/java/mocacong/server/repository/ReviewRepository.java
  src/main/java/mocacong/server/repository/StudyTypeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/domain/StudyTypeTest.java
  src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
  src/test/java/mocacong/server/repository/StudyTypeRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현, 리팩터링
