Repository mocacong/Mocacong-Backend, pull requests merged in 2023-12, with the labels that each got.

#136 feat: 마이페이지 회원 작성 댓글 목록 조회 시, 카페 별로 필터링되도록 구현
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경, 기능 구현

#137 feat: 마이페이지 카페 조회 시 roadAddress 및 내가 남긴 리뷰 함께 조회 기능 구현
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/dto/request/CafeRegisterRequest.java
  src/main/java/mocacong/server/dto/response/FindCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
  src/main/java/mocacong/server/dto/response/PreviewCafeResponse.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/CommentLikeAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/ReportAcceptanceTest.java
  src/test/java/mocacong/server/domain/BaseTimeTest.java
  src/test/java/mocacong/server/domain/CafeImageTest.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/domain/CommentTest.java
  src/test/java/mocacong/server/domain/ScoreTest.java
  src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/repository/CommentLikeRepositoryTest.java
  src/test/java/mocacong/server/repository/CommentRepositoryTest.java
  src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
  src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
  src/test/java/mocacong/server/repository/ScoreRepositoryTest.java
  src/test/java/mocacong/server/service/CafeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentLikeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CommentLikeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteConcurrentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
  src/test/java/mocacong/server/service/ReportConcurrentServiceTest.java
  src/test/java/mocacong/server/service/ReportServiceTest.java
Labels: api 변경

#141 fix: MyCommentCafeResponse에서의 comments 필드명 변경
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#140 fix: 카페 이미지 3개 초과하여 저장 시 예외 반환하는 로직 버그 수정
  src/main/java/mocacong/server/exception/badrequest/ExceedCageImagesTotalCountsException.java
  src/main/java/mocacong/server/service/CafeService.java
Labels: 사소한 버그

#143 feat: MyCommentCafeResponse DTO에 score 필드 추가
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
Labels: api 변경

#146 fix: Token 객체 TTL 시간 단위 이슈 해결
  src/main/java/mocacong/server/service/RefreshTokenService.java
  src/main/resources/application.yml
Labels: 🚨심각한 버그🚨

#147 feat: 코드 정적 분석을 위한 Jacoco 및 SonarCloud 도입
  .github/workflows/ci-backend.yml
  build.gradle
Labels: 인프라

#134 feat: 멤버 논리적 삭제 구현
  src/main/java/mocacong/server/config/BatchConfig.java
  src/main/java/mocacong/server/domain/DeletedMember.java
  src/main/java/mocacong/server/repository/DeletedMemberRepository.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/repository/DeletedMemberRepositoryTest.java
  src/test/java/mocacong/server/repository/MemberRepositoryTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: api 변경

#148 fix: 소나클라우드 커버리지 대상 exclusions 범위 수정
  build.gradle
Labels: 인프라
