Repository mocacong/Mocacong-Backend, pull requests merged in 2023-06, with the labels that each got.

#91 fix: 자체 로그인 캐싱 제거
  src/main/java/mocacong/server/config/RedisCacheConfig.java
  src/main/java/mocacong/server/service/AuthService.java
Labels: 🚨심각한 버그🚨

#92 fix: save 메소드 동시성 문제 해결
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/domain/Favorite.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/domain/Review.java
  src/main/java/mocacong/server/domain/Score.java
  src/main/java/mocacong/server/exception/badrequest/DuplicateCafeException.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/service/CafeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteConcurrentServiceTest.java
  src/test/java/mocacong/server/service/MemberConcurrentServiceTest.java
Labels: 🚨심각한 버그🚨

#93 feat: 운영 서버 배포를 위한 develop 브랜치 트리거 삭제
  .github/workflows/cd-backend.yml
Labels: 인프라

#96 fix: 카페 세부정보 수정 후 결과 반환 시 null 허용
  src/main/java/mocacong/server/domain/Score.java
  src/main/java/mocacong/server/dto/response/CafeReviewUpdateResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 사소한 버그

#97 feat: Multipart 요청 예외 및 잘못된 파라미터 예외 핸들링
  src/main/java/mocacong/server/controller/ControllerAdvice.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/resources/images/test_img.jpg
  src/test/resources/images/test_img2.jpg
Labels: 기능 구현, 리팩터링

#100 feat: 응답값을 로그에 남기도록 구현
  src/main/java/mocacong/server/support/logging/LoggingAspect.java
Labels: 기능 구현

#99 fix: 이메일과 플랫폼 일치 여부를 확인하는 회원 중복 체크로 변경
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
Labels: 🚨심각한 버그🚨

#101 feat: 회원 탈퇴 시, 프로필 이미지 연동 해제 기능 구현
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 사소한 버그, 리팩터링

#102 fix: 누락된 `@Valid` 추가
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/domain/Comment.java
  src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
  src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
Labels: 사소한 버그

#103 fix: studyType별 카페 필터링 로직 both 함께 반환하도록 변경
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#104 fix: 나의 스터디타입 필드 null 불가능하도록 변경
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
  src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
Labels: api 변경

#108 feat: 리뷰 수정 시 카페 미리보기 캐시 무효화
  src/main/java/mocacong/server/service/CafeService.java
Labels: 🚨심각한 버그🚨

#105 fix: 카페 이미지 조회 GET API 로직 최근 순으로 정렬하도록 수정
  src/main/java/mocacong/server/repository/CafeImageRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#106 fix: 카페 이미지 등록 시 회원탈퇴가 불가능한 버그 수정
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/repository/CafeImageRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/java/mocacong/server/service/event/DeleteMemberEvent.java
  src/test/java/mocacong/server/domain/CafeImageTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 🚨심각한 버그🚨

#109 feat: 파일 손상 및 요청 에러 예외 핸들링
  src/main/java/mocacong/server/controller/ControllerAdvice.java
  src/main/java/mocacong/server/exception/badrequest/InvalidFileEmptyException.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/support/AwsS3Uploader.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: 기능 구현

#110 fix: 카페 이미지 조회 정렬 로직 ASC로 수정
  src/main/java/mocacong/server/repository/CafeImageRepository.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경

#107 feat: 전화번호 컬럼 삭제
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/dto/request/MemberProfileUpdateRequest.java
  src/main/java/mocacong/server/dto/request/MemberSignUpRequest.java
  src/main/java/mocacong/server/dto/response/GetUpdateProfileInfoResponse.java
  src/main/java/mocacong/server/dto/response/MemberGetResponse.java
  src/main/java/mocacong/server/dto/response/MyPageResponse.java
  src/main/java/mocacong/server/exception/badrequest/InvalidPhoneException.java
  src/main/java/mocacong/server/service/MemberService.java
  src/main/resources/logback-spring.xml
  src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
  src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
  src/test/java/mocacong/server/domain/BaseTimeTest.java
  src/test/java/mocacong/server/domain/CafeTest.java
  src/test/java/mocacong/server/domain/CommentTest.java
  src/test/java/mocacong/server/domain/MemberTest.java
  src/test/java/mocacong/server/domain/ScoreTest.java
  src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
  src/test/java/mocacong/server/repository/MemberRepositoryTest.java
  src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
  src/test/java/mocacong/server/repository/ScoreRepositoryTest.java
  src/test/java/mocacong/server/service/AuthServiceTest.java
  src/test/java/mocacong/server/service/CafeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteConcurrentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
  src/test/java/mocacong/server/service/MemberConcurrentServiceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: api 변경

#111 feat: 마이페이지 카페 조회 시, 스터디타입을 함께 반환하도록 구현
  src/main/java/mocacong/server/domain/Cafe.java
  src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
  src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/domain/CafeTest.java
Labels: api 변경

#113 fix: 회원가입 시 이메일 확인 로직과 이메일 중복체크 로직 동일
  src/main/java/mocacong/server/controller/CafeController.java
  src/main/java/mocacong/server/controller/CommentController.java
  src/main/java/mocacong/server/controller/FavoriteController.java
  src/main/java/mocacong/server/controller/MemberController.java
  src/main/java/mocacong/server/domain/Member.java
  src/main/java/mocacong/server/repository/CafeRepository.java
  src/main/java/mocacong/server/repository/MemberRepository.java
  src/main/java/mocacong/server/security/auth/AuthenticationPrincipalArgumentResolver.java
  src/main/java/mocacong/server/security/auth/JwtTokenProvider.java
  src/main/java/mocacong/server/security/auth/LoginUserId.java
  src/main/java/mocacong/server/service/AuthService.java
  src/main/java/mocacong/server/service/CafeService.java
  src/main/java/mocacong/server/service/CommentService.java
  src/main/java/mocacong/server/service/FavoriteService.java
  src/main/java/mocacong/server/service/MemberService.java
  src/test/java/mocacong/server/repository/CafeRepositoryTest.java
  src/test/java/mocacong/server/security/auth/JwtTokenProviderTest.java
  src/test/java/mocacong/server/service/CafeConcurrentServiceTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
  src/test/java/mocacong/server/service/CommentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteConcurrentServiceTest.java
  src/test/java/mocacong/server/service/FavoriteServiceTest.java
  src/test/java/mocacong/server/service/MemberServiceTest.java
Labels: 🚨심각한 버그🚨, api 변경

#114 feat: 카페 이미지 url 수정 시 동일 id 반환하도록 로직 변경
  src/main/java/mocacong/server/domain/CafeImage.java
  src/main/java/mocacong/server/service/CafeService.java
  src/test/java/mocacong/server/domain/CafeImageTest.java
  src/test/java/mocacong/server/service/CafeServiceTest.java
Labels: api 변경, 사소한 버그

#112 feat: README 파일 작성
  README.md
Labels: 문서화
